### ISSUE TITLE
New to coffee - requiring a little explanation

### ISSUE THREAD

**Issue by Lithimlin** [SyntaxColoring/Markov-Word-Generator#3]
What do these lines do?:
```
generate: ->
		result = []
		currentState = => # Returns at most the last @ elements of result.
			result[Math.max(0, result.length-@n)...result.length]
		continuation = => @continue(currentState())
		while result.length < @maxLength and (nextElement = continuation())?
			result.push nextElement
return result
```
I understand that an empty array is created and then something is done with `currentState`, but I don't quite understand what it is. Does this `result[Math.max(0, result.length-@n)...result.length]` take the last x letters of the result and assigns it to `currentState`?
The `while` part probably gets a new element to add to the array until `continue(currentState())` returns `Null`, correct? Does the while count for the entire thing though or how is `currentState` reassigned? Or should I look at it in a functional manner, where `currentState` is always the last x letters of result?

**Comment by Lithimlin** [comment]
I think I now understood how these lines of code work.
However, now the methods `ngrams` and `tree` got me confused. Would you mind explaining how they work?

**Comment by SyntaxColoring** [comment]
Sure, @Lithimlin.

#### The `generate` method

`currentState` and `continuation` are both helper *functions,* not variables that are being reassigned.

`currentState` normally just returns the last `@n` letters.  (The comment there has a typo, I guess.)  The tricky part is at the beginning of the string where we don't have any letters.  In that case it returns as many as it can.

`continuation` returns the next letter based on what `currentState()` can provide.

There while-loop, as you suspected, just iteratively pushes new letters onto `result` until either `continuation()` returns null or it reaches a maximum length.  There's nothing functional going on.

#### The `ngrams` method

N-grams are groups of *n* consecutive elements, as they appeared in the source corpus.  For example, if your input is the single word `mississippi`, the 3-grams would be `mis`, `iss`, `ssi`, `sis`, `iss`, `ssi`, `sip`, `ipp`, `ppi`. 

 That's what the `ngramsFromSequence` nested function returns.

When the input is multiple words, like `[sassafras, mississippi]`, we need to extract the n-grams from each word separately.  If we extracted the n-grams from the concatenation of all the words, we would end up with n-grams crossing the border between words, like `asm` and `smi`, which doesn't make sense.  So the `reduce` simply runs `ngramsFromSequence` on each word separately and then concatenates the results together so `ngrams` can return a single array.

#### The `tree` method

Given that we can compute an array of n-grams, we want to turn that into a structure that more naturally represents which letter is most likely to appear given the previous *n-1* letters.  We use a tree *n* nodes deep, where each node is one letter, and its children are the letters that can come after it.

Behold my programmer art:

```
3-grams: [ssi, sis, iss, ssi, sip]

   [Start]
   /    \
  /      \
 /        \
i,1       s,4
|          / \
|         /   \
|        /     \
s,1     i,2     s,2
|      / \      |
s,1   p,1 s,1   i,2

```

At each node, the number next to it represents how many times that letter occurred after the sequence of letters represented by its chain of parents.  So, in this tree, after the two letters `si`, it is equally likely that the third is either `p` or `s`.

This is what the first for-loop in `tree` builds.

The `normalize` step converts those absolute integer counts into relative frequencies.  So instead of 1 and 1, we get 0.5 and 0.5.  This is just for convenience.

As a final step, instead of returning the entire tree, we return only the subtree that the caller is interested in, represented by the `sequence` argument.  Again, just for convenience.  The `reduce` there is just a cute way of traversing the tree up to that point.  It's equivalent to doing `currentNode = currentNode.continuations[sequence[i]]` in a for-loop, except that if it encounters a null node, it returns null instead of running into an error.  Handling null correctly is important because it represents a "dead end," e.g. in the original corpus, that sequence of letters always appeared at the very end of a word, and it's impossible for anything to come after it.

<hr>

Does this help?

Reading this code for the first time in several years, I'm finding this a horribly inefficient way to do things.  We currently compute the probability tree from scratch for each new letter that's generated.  We should only need to do it once, when the corpus is read in.  But I guess I prioritized simplicity over performance when I wrote it.

**Comment by Lithimlin** [comment]
Okay, so you were able to confirm my understanding of the code.
However, the [python code I wrote](https://pastebin.com/B8abHA0Y) does not seem to work. It might be a very obvious mistake that I'm missing. Maybe you could help me to point them out.

**Comment by Lithimlin** [comment]
Okay, so you were able to confirm my understanding of the code.
However, the [python code I wrote](https://pastebin.com/B8abHA0Y) does not seem to work. It might be a very obvious mistake that I'm missing. Maybe you could help me to point them out.

**Comment by SyntaxColoring** [comment]
Frankly, there's a lot mechanically wrong with that code.  Specifically:

1. The default argument `continuations = dict()` will [not do what you expect.](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments)
2. You want to append the result of calling `nextElement()` but instead you're appending the `nextElement` function itself.
3. `ngrams()` should return a flat array, but because you're using `append()`, you're returning an array of arrays.  You probably want `+=` or `extend()`.
4. When you iterate over a `dict` in a `for` loop, you get the key even though you might expect to get the value.

That's as far as I got.  There might be more problems.

It looks like you're trying to translate the entire CoffeeScript source into Python at once.  That's going to be tricky.  You'll probably find it much easier to write and test your program in increments.  Start with `ngrams()` and test it well to make sure it behaves exactly as you expect, especially in weird cases.  *Then,* move on to `tree()` and do the same.  Finally, do `generate()`.

And remember that my architecture is only one possible way to implement a Markov chain.  Mimicking it is fine to start, but you may find that the most elegant solutions in Python aren't the same as the most elegant solutions in CoffeeScript.

Of course I'm still happy to help if it continues to give you trouble.

**Comment by Lithimlin** [comment]
>     `ngrams()` should return a flat array

I've now reached that point.

> where each node is one letter, and its children are the letters that can come after it.

So what would given into the `tree()` function? A single letter or a sequence of n letters?

**Comment by SyntaxColoring** [comment]
> So what would given into the `tree()` function? A single letter or a sequence of n letters?

The next letter is dependent on the previous *n* letters.  So `tree()` should take that sequence of *n* letters.

Another way of doing it would be for `tree()` not to take any arguments and return the entire tree.  Then it's the caller's responsibility to traverse the tree.

**Comment by Lithimlin** [comment]
So should it return a single letter or a sequence of n letters? Probably the latter, right?

**Comment by SyntaxColoring** [comment]
Nope.  I have it return a single letter at a time.  Remember that the Markov chain looks back at the previous n letters for *each* new letter that it appends.  The Markov chain can't output two letters at once because the second one depends on its choice of the first one.

**Comment by Lithimlin** [comment]
Thank you very much! I've (partly) finished my version. You can find it [here](https://github.com/Lithimlin/Markov-Name-Generator) if you wanna take a look at it.

**Comment by SyntaxColoring** [comment]
No problem, and thanks for linking your project.  Looks good!

Feel free to ask here again if you need any more help.
