### ISSUE TITLE
How many possibilities?

### ISSUE THREAD

**Issue by geraldhiller** [SyntaxColoring/Markov-Word-Generator#4]
Not really an issue, but rather a question. I was wondering if you know off the top of your head how many possible words this algorithm will generate dependent on the number of words in the seed list. Thanks a lot for your help!

**Comment by SyntaxColoring** [comment]
Interesting question.

If the output length isn't capped, it's theoretically infinite, because it can get caught in a loop.  For example, if your seed list is `["abba"]` and `n`=1, it can generate "aba", "abab", "ababa", "ababab", and so on, without limit.

If the output length is capped, then it's dependent not just on the number of words on the seed list but also the structure of those words. The more distinct n-grams appear, the more possibilities there are.  I don't think there's a useful closed-form formula; I would enumerate the possibilities exhaustively if I needed an exact answer.
